name: your_new_project_name

services:
  ais.api:
    image: ${DOCKER_REGISTRY-}accountabilityinformationsystemapi
    build:
      context: .
      dockerfile: AccountabilityInformationSystem.Api/Dockerfile
    ports:
      - 4000:8080
      - 4001:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ais.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    
  ais.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
